apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        name: nginx
        version: "blue"
    spec:
      containers: 
        - name: nginx
          image: nginx:blue
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
