apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-green
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: nginx
        version: "green"
    spec:
      containers: 
        - name: nginx
          image: nginx:green
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
